### ISSUE TITLE
Speed up tests by running pytest in parallel

### ISSUE THREAD

**Issue by dhruvkelawala** [jediswaplabs/JediSwap#12]
Let's use pytest-xdist and run tests in parallel on github-actions

**Comment by milancermak** [comment]
Note that with GitHub actions, you'll only get 2 cores, so the speedup is limited (but still worth it IMO).

Also, `pytest-xdist` suppresses test output - the `-s` option has no effect.

**Comment by princearoragithub** [comment]
Not needed as we moved to Protostar.
